 /******************************************************
 * PLEASE DO NOT EDIT THIS FILE
 * the verification process may break
 * ***************************************************/

'use strict';

var fs = require('fs');
var express = require('express');
const GoogleImages = require('google-images');
const client = new GoogleImages(process.env.CSE_KEY, process.env.GOOGLEAPI_KEY);
var app = express();

if (!process.env.DISABLE_XORIGIN) {
  app.use(function(req, res, next) {
    var allowedOrigins = ['https://narrow-plane.gomix.me', 'https://www.freecodecamp.com'];
    var origin = req.headers.origin || '*';
    if(!process.env.XORIG_RESTRICT || allowedOrigins.indexOf(origin) > -1){
         console.log(origin);
         res.setHeader('Access-Control-Allow-Origin', origin);
         res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    }
    next();
  });
}

app.use('/public', express.static(process.cwd() + '/public'));

app.route('/_api/package.json')
  .get(function(req, res, next) {
    console.log('requested');
    fs.readFile(__dirname + '/package.json', function(err, data) {
      if(err) return next(err);
      res.type('txt').send(data.toString());
    });
  });

app.route('/test:offset').get(function(req, res, next) {
  console.log(req);
  var offset = parseInt( req.param.offset) +0;
  console.log("offset ", req.param.offset);
  if(offset<=0){
  offset=1;
  }
client.search('walking dead',{page: offset})
	.then(images => {
/*
		[
    {
      type: "image/jpeg",
      width: 3600,
      height: 2403,
      size: 1047219,
      url: "http://static2.businessinsider.com/image/56bb5129dd08958c148b470a-3600-2403/the-walking-dead-zombies.jpg",
      thumbnail: {
        url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSRpurq3kfA3kvVA62f595fiaaPoZro8bKfxGDug__6X5Q0iqRtQLpR8pqf",
        width: 150,
        height: 100
      },
      description: "The Walking Dead' used zombie dentures with blood in mid-season ...",
      parentPage: "http://www.businessinsider.com/walking-dead-zombie-dentures-mid-season-premiere-2016-2"
    }
    ]
*/
    res.send(JSON.stringify(images));
  }).catch(err => {
    res.send(err);
  })
});




  
app.route('/')
    .get(function(req, res) {
		  res.sendFile(process.cwd() + '/views/index.html');
    })

// Respond not found to all the wrong routes
app.use(function(req, res, next){
  res.status(404);
  res.type('txt').send('Not found');
});

// Error Middleware
app.use(function(err, req, res, next) {
  if(err) {
    res.status(err.status || 500)
      .type('txt')
      .send(err.message || 'SERVER ERROR');
  }  
})

app.listen(process.env.PORT, function () {
  console.log('Node.js listening ...');
});

